[package]
authors = ["Steve Sosik"]
edition = "2021"
name = "advent-of-code-2022"
version = "0.1.0"
[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.10.5"
phf = { version = "0.11", features = ["macros"] }

[lib]
bench = false
